---
Name: app-config
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

SilverStripe\i18n\i18n:
  default_locale: 'nl_NL'

SilverStripe\Assets\File:
  # apply_restrictions_to_admin: false
  # NOTE: need to add these extensions to assets/.htaccess as well, else they can be uploaded but not downloaded
  allowed_extensions:
    - svg
    - xlsm

SilverStripe\SiteConfig\SiteConfig:
  rearrange_access_fields: true
  enable_contact_social_media_fields: true
#  enable_browser_color_theme_field: true
  enable_browser_color_theme_field: '#ff0000'
  enable_logo_upload_fields: true
  enable_raw_head_body_fields: true
#  enable_subnav_activation_field: true
  theme_subnav_slots:
    - 'before'
    - 'after'
    - 'below'


# Add Emoji support, may give issues with too long indices https://github.com/silverstripe/silverstripe-framework/issues/8062
---
Name: app-database
---
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
